server:
  port: 811

db:
  host: localhost
  port: 3306
  name: test

spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 970811
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 60000
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      allow-pool-suspension: true
      pool-name: DatabasePool
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml

task:
  cron: 0 10 0 * * ?
  push:
    dedeuserid:
tencent:
  secret-id:
  secret-key:
  cos-region:
  bucket-name:
  folder: avatars